### ISSUE TITLE
홈페이지 수정 사항을 요청합니다.

### ISSUE THREAD

**Issue by nhyunwoo** [Taebu/ezrachurch#18]
1. http://ezrachurch.kr
http://ezrachurch.kr/wp/bbs/lecture_list.php
위의 두 페이지에 "4박5일 팝업창" 부탁드립니다.

2. 팝업창을 클릭하면 접수창으로 가게 하이퍼링크 부탁드립니다.

3. http://ezrachurch.kr/wp/bbs/lecture_list.php
위 페이지에서 붉은색 "접수중(신청하기)"를 클릭 했을 때,
로그인인 및 회원 가입을 안 한 분들은 
바로~ 회원 가입 페이지로 연결되게 안내 부탁드립니다.

★팝업창 이미지.jpg 파일은 제가 카톡으로 보내 드리겠습니다.

늘 노고에 감사드립니다.

**Comment by Taebu** [comment]
1. 적용완료 
2. 적용완료
3. 적용완료
