### ISSUE TITLE
팝업창 이미지 올려드립니다. 몇가지 수정사항도 ..

### ISSUE THREAD

**Issue by nhyunwoo** [Taebu/ezrachurch#19]
1. 아래 이미지를 
http://ezrachurch.kr/wp/bbs/content.php?co_id=ezrabible
와
http://ezrachurch.kr/wp/index.php
에 두곳에 팝업 창으로 뜨게 해주세요. 

2. 팝창을 클릭하면
http://ezrachurch.kr/wp/bbs/lecture_list.php
로 가게 해주세요.

![2017-9th-sum](https://user-images.githubusercontent.com/30034255/28003937-21b8ad62-657c-11e7-81de-6efdd72d31b0.jpg)

3. 그리고 회원가입이 안되어 있는 분이
http://ezrachurch.kr/wp/bbs/lecture_list.php
여기서 '접수중(신청하기)'를 클릭하면 회원 가입 페이지로 가게 해주시고

4. 회원가입 절차를 마치고 완료하면다시
http://ezrachurch.kr/wp/bbs/lecture_list.php 로 오셔서 바로 접수 할 수 있도록 부탁드립니다.

바쁘신데 감사드립니다.

**Comment by Taebu** [comment]
1. http://ezrachurch.kr/wp/bbs/content.php?co_id=ezrabible
- 여기는 팝업이 어렵습니다.
메인은 팝업 설정 되었습니다.

2. 적용 완료

3. 적용완료 

4. 이건 로그인 회원이 자꾸 이 페이지로 가는 것은 무리 인것 같습니다.
- 이건 보류 토록 하겠습니다. 이용 불편에 대한 이슈가 또 생길 것으로 보입니다.

**Comment by nhyunwoo** [comment]
그러면 1.http://ezrachurch.kr/wp/bbs/content.php?co_id=ezrabible 에 접수로 바로 가는 배너라도 하나 만들어주세요. ^^
