### ISSUE TITLE
에스라바이블스쿨 교육 게시판 기능 부탁해요

### ISSUE THREAD

**Issue by nhyunwoo** [Taebu/ezrachurch#21]
http://ezrachurch.kr/wp/bbs/board.php?bo_table=bsc_edu&page=

위의 페이지에서도 유튜브 영상 주소를 링크하면 자동으로 플레이어가 게시물에 뜨게 해주세요.

에스라바이블스쿨 사진앨범방은 되는데 여기 교육 게시판에서는 안되서요~ 부탁해요

**Comment by Taebu** [comment]
스킨 페이지로 해당 게시판은 변경 하였습니다.
