### ISSUE TITLE
교회 홈페이지 섬기는이 수정 요청

### ISSUE THREAD

**Issue by nhyunwoo** [Taebu/ezrachurch#25]
http://ezrachurch.kr/wp/bbs/content.php?co_id=helper

1. 위 페이지에 저와 간사님 사진 크기를 아래 다른 분들 사진 모양과 크기를 같게 해 주시기 바랍니다.

2. 쇼파르 단원에 심하은 자매를 넣어 주시기 바랍니다.

3. 양호상, 이화자 권사님 이름에 하이퍼링크를 없애 주시기 바랍니다.

감사합니다.

**Comment by Taebu** [comment]
모두 적용 하였습니다.
- 홍슬기 집사님께 이미지 수정 요청 하였습니다.
- 링크에 대한 것은 원래 상세 페이지가 있는데 필요하시다면 차후 작업 토록 하겠습니다. 요청대로 모두 삭제 하였습니다.
