### ISSUE TITLE
성경 질문과 답변 게시판 요청

### ISSUE THREAD

**Issue by nhyunwoo** [Taebu/ezrachurch#32]
http://ezrachurch.kr/wp/bbs/board.php?bo_table=data_01

페이지에다가 <성경 질문과 답변> 게시판을 하나 만들어 주시면 대단히 감사하겠습니다.

성경질문을 하는 성도들이 계시는 내용이 한번 개인적으로 답변해주고 없어지는 것을 축적하기 위함입니다. 감사합니다.

**Comment by nhyunwoo** [comment]
질문 게시판도 주일설교처럼 
창~계 까지 메뉴로 나눠주면 감사하겠습니다.

**Comment by Taebu** [comment]
스킨을 만드는 작업이 있어야 해서 시간이 좀 걸릴 것으로 사료 됩니다. 카테고리를 창~계로 등록 해서 왼쪽에서 선택하면 보이게 해달라는 말씀이신거죠?

**Comment by nhyunwoo** [comment]
네 성경질문과 답변게시판은 그렇게 부탁드립니다.

젓페이지는 질문했던 <전체 목록>이 최신순으로 뜨게 부탁드립니다.

**Comment by Taebu** [comment]
네 알겠습니다

**Comment by Taebu** [comment]
<img width="1092" alt="qna" src="https://user-images.githubusercontent.com/7663572/48599846-da3ede00-e9ac-11e8-84bc-15e05d99b5e5.png">
적용 했습니다.

**Comment by nhyunwoo** [comment]
카테고리 선택 안하면 글 못남기게 했나요?

우리교회 단톡에 광고해주세용

**Comment by Taebu** [comment]
네
