### ISSUE TITLE
부교역자실 방 공유기 전원 정리 부탁 드립니다.

### ISSUE THREAD

**Issue by nhyunwoo** [Taebu/ezrachurch#33]
공유기를 발로 치거나 전원이 내려갈 수 있는 일들이 발생할 수 있어서 요청 드립니다.

**Comment by Taebu** [comment]
https://twom.myds.me/bbs/board.php?bo_table=img_ge&wr_id=27
![3554560211_cmrrk3ct_669dc37a33d8eba7133ff439014f127a1c501c4a](https://user-images.githubusercontent.com/7663572/48600019-8aace200-e9ad-11e8-8521-dcbe35d97ca0.jpg)
![thumb-3554560211_c5ukjywq_797b2e8d407b3fc1879fca46d4bce1a56e74f65b_600x450](https://user-images.githubusercontent.com/7663572/48600020-8b457880-e9ad-11e8-9bc9-d9e14e7ff105.jpg)
우리집 네트워크 장비 8포트 허브 추가 



집에 공유기나 모뎀 장비로 인해 tv주변이 너무 더럽고 청소가 힘들어서..

철망으로 구성을 하였다가...



이번에 8포트 허브를 구매하여 기가랜 구성을 추가하였는데..

처음의도한것과는 달리...



귀차니즘..!!!



결국 대충하다보니...이거 더 지저분해 보인다..

- 이곳을 참조 하여 진행 하겠습니다.

**Comment by Taebu** [comment]
![default](https://user-images.githubusercontent.com/7663572/48600095-d2336e00-e9ad-11e8-9aa2-feadd475a79a.jpg)
완료 되었습니다.
