### ISSUE TITLE
사이트 검색 문제

### ISSUE THREAD

**Issue by nhyunwoo** [Taebu/ezrachurch#35]
http://ezrachurch.kr/wm/list.php

그리고 태부형제님 이사이트에서 검색이 되었으면 좋겠습니다.

**Comment by Taebu** [comment]
검색은 구현 되었습니다.

**Comment by Taebu** [comment]
![image](https://user-images.githubusercontent.com/7663572/48600393-f8a5d900-e9ae-11e8-92ae-b9d9691142e2.png)
