### ISSUE TITLE
 홈페이지 교역자소개란에 '심기호'전도사님 추가 바랍니다.

### ISSUE THREAD

**Issue by nhyunwoo** [Taebu/ezrachurch#36]
http://ezrachurch.kr/wp/bbs/content.php?co_id=helper

![001](https://user-images.githubusercontent.com/30034255/49585229-1dcfab00-f9a1-11e8-9ef4-43ec382204dc.jpg)

**Comment by Taebu** [comment]
![image](https://user-images.githubusercontent.com/7663572/49627399-fa991000-fa21-11e8-9de6-c9e70dd96ee1.png)
약력은 경력 사항을 참고 하였습니다. 목사님의 권고에 따라 수정하거나 직접 수정하셔도 될 것으로 보입니다.
