### ISSUE TITLE
교역자들 주보 업무 페이지 요청의 건

### ISSUE THREAD

**Issue by namgunghyunwoo** [Taebu/ezrachurch#46]
https://ezrachurch.kr/WeeklyNews.php  를 하나 만드셔서
달력을 표기해 주시고 달력에 주일을 클릭하면 주일 주보내용을 기록할 수 있는 페이지가 나오면 좋겠습니다.

앞으로 주보는 부교역자가 만들기로 했습니다.
그래서 담임 필요한 광고나 내용을 위 페이지에 기록해서 교역자들이 어디서든 다음주 주일 주보에 들어갈 내용을 확인하는 페이지가 되었으면 합니다.

주보는 총 6면으로 되어 있으니 칸이 구분되면 더욱 좋겠습니다.
문프로그래머의 실력을 믿습니다. 샬롬.!

**Comment by Taebu** [comment]
우선 계락적인 달력 디자인 UI가 필요 합니다.
그리고 주일 주보 내용이 디자인 요소가 많아서 거의 포토샵에 가까운 작업을 HWP로 구현 하신거라 웹상에서는 그렇게 화려하게 구성하기 어렵습니다.
그리고 이런 요청은 개발 자체가 어려운 점을 양혜바랍니다.
기본적으로 프로그램은 데이터를 받는 
입력 값
그리고 
출력 값이 존재 합니다.

주보는 거의 대부분이 입출력이 같기 때문에 크게 어려울게 없다고 생각하실 수도 있지만 그걸 다 일일히 데이터형을 맞추고 한글 영문 데이터 타입을 다 맞춰야 합니다.

No|한글|영문|dataType|입출력형태|comment
--|--|--|--|--|--
1|오전 찬송가1|amHymn1|정수|입력
2|오전 찬송가2|amHymn2|정수|입력
3|오전 시편1|amPsalm1|정수|입력
4|오전 시편2|amPsalm2|정수|입력

...중략

이게 다 정해지고 나서도 입출력 형태 레이아웃을 주보에 맞게 그리고 출력 형태 까지 심지어 말씀하신 주보형태를 달력 형태로 까지 만드는 것은 저로서는 보지 못했습니다.
그리고 웹으로 입력을 받는 폼 자체가 횡 스크롤 형태로 위에서 아래로 쭉 입력 하여 나열식으로 입력 되는 형태인데 주보는 특정 위치에 위치 해 있어야 하고 특정 위치에 범주를 넘어서 텍스트 길이가 조금이라도 길어지면 레이아웃 전체가 망가지는 기형적인 구조를 지니고 있습니다.

기존의 주보 형태가 아닌 횡 스크롤 형태의 웹으로 된 주보의 레이아웃이 필요하시다면 쉽게 구현 가능 하지만 지금 형태의 HWP 주보로의 웹구현은 구현이 더딜 것으로 생각 합니다.

그리고 말씀 해주신 기능을 구현하려면 아래 네 가지 최소 조건을 만족 해야 합니다.

1. 입출력 구조표 (위에 테이블 예시 제공)

2. write
웹 주보 입력 디자인 구성 

3. list
웹주보 달력 디자인 출력 형태

4. modify
웹 주보 수정 디자인 구성


위에 네 가지가 다 구성되고 나서도 구현이 어려운 것은 디자인 수정을 해 나가야 하며 말씀 해주신 기능 들은 디자이너나 기획자 테스터들이 다 구성되고 나서 말씀 해주시면 협력하여 만들어 볼 수는 있을 것 같습니다.

**Comment by Taebu** [comment]
그리고 이 웹 주보 부분은 어떻게 기획 되느냐에 따라 기간에 장기화 프로그램 난이도에 따라서 부득이 비용청구가 될 수 밖에 없다는 점을 고지 합니다. 크게 지금과 같이 주보를 만드시는데 어려움이 없으시다면 개발 재검토 부탁드립니다.

**Comment by namgunghyunwoo** [comment]
아 답변 감사합니다. 그런데 너무 어렵게 생각하시는 것 같습니다.
제가 원하는 것은 누군가 입력만 하면 타인이 그림과 글씨를 볼수만 있으면 됩니다.

즉, 여섯개의 칸이 있고, 거기에 글/그림만 입력할수 있으면 됩니다.


  |   |  
-- | -- | --
  |   |

**Comment by Taebu** [comment]
이야기 취지는 잘 이해 했습니다.

링크에 제공 해달라는 부분 자체가 혼동이 올 수 밖에 없었던 것 같습니다. 해당 링크로 구현 하는 것이야 말로 모든 기능을 다 생으로 그누보드에 해당하는 모든 게시판 기능을 구현해야 하는 부분이기에 개발 비용을 상고 한 것입니다. 이 링크로 개발하게 되면 에디터및 모든 기능을 제가 혼자 다 구현해야 했기에 그렇게 되면 끝이 없는 개발이 시작 될 것입니다.

그리고 언급하신 부분은 그누보드에 스킨을 추가해 제공한다면 말씀하신 것처럼 쉽게 구현이 될것으로 생각 됩니다. 다만 말씀하신 출력기능이 제대로 작동할 지는 장담할 수 없습니다.

그리고 앞서 말씀드린것과 같이 네 가지 요청 사항을 수용하시고 게시글을 올리는 모든 기능을 담은 

리스트
뷰
수정
글쓰기

위 네가지를 포토샵이나 그림판으로라도 작업을 하신 후 작업 요청 바랍니다. 

제가 위에 그림을 보고도 어렵다는 말이 안나오도록 스킨 개발에 대한 디자인 제공 바랍니다. 위 네가지 사항이 수용되지 않는다면 남궁현우 목사님께서 말씀하신 간단한 개발조차 시작할 수 없음을 알립니다. 

개집도 설계도가 있다고 남궁목사님께서 말씀하셨죠? 

아무리 간단한 개발이라도 설계도도 없이 개발 진행이 불가 함을 알립니다. 최소한의 작업요청을 원한 건데 이렇게 일방적으로 간단하다. 어렵게 생각한다. 뭐뭐만 볼 수 있으면 됩니다. 제가 요청 드린 절차 무시하고 이런식으로 요청하지 않으셨으면 좋겠습니다.

계속 이런식으로 어렵게 생각한다 ~~만 볼수 있으면 됩니다. 몇글자 첨언으로 작업 요청 하시면 개발 진행이 어렵습니다.

**Comment by namgunghyunwoo** [comment]
여섯개(A4 사이즈 세칸 양면)의 칸이 있고, 거기에 글/그림만 입력할수 있으면 됩니다.

출력은 안해도 됩니다.

위의 웹 페이지를 보고 유져들이 따로 한글 주보를 만들어서 출력할 것입니다.

즉, 게시판 처럼 정보 전달, 내용 공유만 되면 됩니다. 

잘 부탁드립니다.

**Comment by namgunghyunwoo** [comment]
![서울에스라교회 주보 내용001](https://user-images.githubusercontent.com/60363694/73595679-bab6b580-455e-11ea-881f-363a400d3950.jpg)

**Comment by Taebu** [comment]
```sql
ALTER TABLE `newezra`.`g5_write_jubo` 
CHANGE COLUMN `wr_1` `wr_1` TEXT NOT NULL ,
CHANGE COLUMN `wr_2` `wr_2` TEXT NOT NULL ,
CHANGE COLUMN `wr_3` `wr_3` TEXT NOT NULL ,
CHANGE COLUMN `wr_4` `wr_4` TEXT NOT NULL ,
CHANGE COLUMN `wr_5` `wr_5` TEXT NOT NULL ;

```

**Comment by Taebu** [comment]
![스크린샷 2020-02-05 00 08 29](https://user-images.githubusercontent.com/7663572/73756905-aca9a480-47ab-11ea-93c5-7fddbd039fbb.png)
![스크린샷 2020-02-05 00 08 15](https://user-images.githubusercontent.com/7663572/73756907-aca9a480-47ab-11ea-8649-230c8a3db859.png)
jubo  스킨 만든것

**Comment by Taebu** [comment]
before code

view.skin
```php
<div id="bo_v_con">
<?php echo get_view_thumbnail($view['content']); //echo $view['rich_content']; // {이미지:0} 과 같은 코드를 사용할 경우
?>
</div>
```

after code
view.skin
```php

<div id="bo_v_con">

<table>
<tr>
<td><?php echo $view['wr_2'];?></td>
<td><?php echo $view['wr_1'];?></td>
<td><?php echo get_view_thumbnail($view['content']);
//echo $view['rich_content']; // {이미지:0} 과 같은 코드를 사용할 경우
?> </td>
</tr>
<tr>
<td><?php echo $view['wr_3'];?></td>
<td><?php echo $view['wr_4'];?></td>
<td><?php echo $view['wr_5'];?></td>
</tr>
</table></div>
```

**Comment by Taebu** [comment]
write.skin.php
```php
<tr>
<th scope="row"><label for="wr_1">주보 1면*
<style>
.highlight{
background: firebrick !important;
}
</style>
<table>
<tr>
<td>주보2면</td>
<td class="highlight">주보1면</td>
<td>주보겉표지</td>
</tr>
<tr>
<td>주보3면</td>
<td>주보4면</td>
<td>주보5면</td>
</tr>
</table>
<strong class="sound_only">필수</strong></label></th>
<td class="wr_1">
<?php if($write_min || $write_max) { ?>
<!-- 최소/최대 글자 수 사용 시 -->
<p id="char_count_desc">이 게시판은 최소 <strong><?php echo $write_min; ?></strong>글자 이상, 최대 <strong><?php echo $write_max; ?></strong>글자 이하까지 글을 쓰실 수 있습니다.</p>
<?php } ?>

<?php echo editor_html("wr_1", $write['wr_1'], $is_dhtml_editor); ?>
<?php if($write_min || $write_max) { ?>
<!-- 최소/최대 글자 수 사용 시 -->
<div id="char_count_wrap"><span id="char_count"></span>글자</div>
<?php } ?>
</td>
</tr>```
