### ISSUE TITLE
게시판 메뉴를 하나더 만들어 주시길 요청합니다.

### ISSUE THREAD

**Issue by namgunghyunwoo** [Taebu/ezrachurch#48]
https://ezrachurch.kr/wp/bbs/content.php?co_id=bsc_intro

위의 에스라바이블스쿨 홈페이지 메뉴에
<자료실>게시판을 하나 개설해 주시기를 요청합니다.

감사합니다.

**Comment by Taebu** [comment]
![image](https://user-images.githubusercontent.com/7663572/77148447-f0920800-6ad2-11ea-8f7d-c495a3932cbd.png)
