### ISSUE TITLE
[스킨]갤러리게시판(list).png

### ISSUE THREAD

**Issue by Taebu** [Taebu/ezrachurch#5]
![list](https://cloud.githubusercontent.com/assets/7663572/20307288/1f149aa8-ab82-11e6-9c0d-ba32b69c5a87.png)

- [x] 1. 썸네일은 글쓰기시 등록한 썸네일 노출
- [x] 2. 마우스 오버시 똑같은 효과로 제목 보여주기
- [ ] 3. 클릭시 글쓰기시 등록된 링크로 새창 띄우기(구글포토로 연결)
- [x] 4. 한 페이지에 9개 노출

**Comment by ilowme** [comment]
가입했어요

**Comment by Taebu** [comment]
넵 최수현 간사님, 남궁현우 목사님 썸네일 작업 부탁드립니다.

그리고

http://anp.cashq.co.kr:82/
여기로 접속하시면 됩니다.
