### ISSUE TITLE
홈페이지 로고 변경 문제

### ISSUE THREAD

**Issue by namgunghyunwoo** [Taebu/ezrachurch#54]
![Cap 2020-05-14 18-12-35-532](https://user-images.githubusercontent.com/60363694/81916496-dbd37b80-960e-11ea-81b5-2d96c24c215d.jpg)
1. 에스라바이블하우스
https://ezrachurch.kr/wp/bbs/content.php?co_id=ezrabible

위 에스라성서원 메뉴를 클릭했을때, 혹은 그 하위 메뉴들을 선택 했을때는 왼쪽 상단에서 서울에스라교회 로고가 아닌 아래 에스라성서원 로고가 나오게 부탁합니다.
![투명로고03](https://user-images.githubusercontent.com/60363694/81797724-217a4080-954a-11ea-9b67-07198152393b.png)

2. 에스라바이블스쿨
https://ezrachurch.kr/wp/bbs/content.php?co_id=bsc_intro

위 에스라성서원 메뉴를 클릭했을때, 혹은 그 하위 메뉴들을 선택 했을때는 왼쪽 상단에서 서울에스라교회 로고가 아닌 아래 에스라바이블하우스 로고가 나오게 부탁합니다.

![투명로고02](https://user-images.githubusercontent.com/60363694/81797827-3bb41e80-954a-11ea-8066-eb22bb1912a4.png)

**Comment by Taebu** [comment]
https://www.tutorialrepublic.com/faq/how-to-check-if-a-string-contains-a-specific-word-in-php.php
```php
<?php
$word = "fox";
$mystring = "The quick brown fox jumps over the lazy dog";
 
// Test if string contains the word 
if(strpos($mystring, $word) !== false){
    echo "Word Found!";
} else{
    echo "Word Not Found!";
}
?>
```

**Comment by Taebu** [comment]
https://ezcode.tistory.com/18
```php
$arr = array("1", "3", "5", "7", "9");  
$chk = "5";  
if(in_array($chk, $arr)) echo "$chk가 있네~"; // 출력  
else echo "$chk는 없군요";  
  
if(in_array($chk, $arr)) echo "$chk가 있네~";  
else echo "$chk는 없군요"; // 출력  


출처: https://ezcode.tistory.com/18 [Ezcode]
```
