### ISSUE TITLE
강좌접수게시판 메뉴 생성문제 부탁드립니다.

### ISSUE THREAD

**Issue by namgunghyunwoo** [Taebu/ezrachurch#55]
![Cap 2020-05-15 03-40-09-003](https://user-images.githubusercontent.com/60363694/81972712-f6811100-965d-11ea-9c4c-dd30d379321d.png)

1. [회차] 칸에다가 1이라고 넣은 다른 강좌가 있으면 또 1 이라고 넣을 수가 없습니다. 
'총신에스라'가 5회차 일수도 있고 '성경강좌'가 5회차일 수도 있는데, 겹치는 회차 숫자를 입력을 못하니 불편합니다. 다른 접수 게시판과 중복되는 숫자도 입력할 수 있게 해주세요.

2. 강의 구분에서 '학술대회' 메뉴를 생성해 주시면 감사히 사용하겠습니다. 접수 창을 어서 만들어야 하오니 속히 부탁을 드립니다. 늘 감사드립니다

**Comment by Taebu** [comment]
![image](https://user-images.githubusercontent.com/7663572/81997661-6ce83800-968b-11ea-832d-ce588a68255c.png)

**Comment by Taebu** [comment]
```sql
ALTER TABLE `newezra`.`ez_lecture` 
DROP INDEX `el_lecture_key` ,
ADD UNIQUE INDEX `el_lecture_key` (`mb_id` ASC, `em_no` ASC);
```
