### ISSUE TITLE
팝업창 작업을 부탁드립니다.

### ISSUE THREAD

**Issue by namgunghyunwoo** [Taebu/ezrachurch#56]
![포스터  에스라성서신학회 제1회 학술대회 포스터](https://user-images.githubusercontent.com/60363694/82108502-d9396900-9769-11ea-9e64-4d05184f8cf4.jpg)

1. 학회회포스터를 교회 홈페이지 메인창에 팝업이 뜨게 부탁드립니다.

2. 팝업이 된 포스터를 클릭하면 메인 인터넷 창이 아래 접수 페이지로 가게 링크도 부탁드립니다. 감사합니다.
https://ezrachurch.kr/wp/bbs/lecture_write.php?em_no=9

**Comment by Taebu** [comment]
팝업은 작업 했습니다.
문제는 지금 이유는 잘 모르겠지만 링크를 걸어도 걸리지 않습니다.
이점은 양혜바랍니다.
