### ISSUE TITLE
답변글을 정식으로 달았는데 노출이 되지않습니다.

### ISSUE THREAD

**Issue by namgunghyunwoo** [Taebu/ezrachurch#58]
https://ezrachurch.kr/wp/bbs/board.php?bo_table=qna&wr_id=1&&#c_30

위 페이지에서 정재훈 님의 글에 답변글을 정식으로 달았는데 노출이 되지않습니다.

일단 댓글로 다시 달아 놨습니다.

**Comment by Taebu** [comment]
댓글로 알렸다 시피 다음페이지에 있어서 리스트에 있었습니다. 이슈를 종료 합니다.
